### ISSUE TITLE
Feature Suggestion: Include a copy code button

### ISSUE THREAD

**Issue by aneeskhan47** [tempestphp/highlight#83]
Hi @brendt,

First of all, thank you for this amazing library for code syntax highlighting, can we include a copy code button with the default provided themes? we can provide CSS classes as well so anyone can customize the styling as well.

**Comment by brendt** [comment]
The problem here is that this package is only concerned about rendering the code itself. Everything outside that scope isn't handled by it. So, for example, people will have to style `pre` blocks that include code themselves. The code will be styled, but the `pre` block not. 

We might reconsider this in a later stage, but for now I don't think we'll add support for stuff like copy buttons.
